"""HTTP dependencies shared by 004 routes."""

from __future__ import annotations

from fastapi import Header, Request

from legal_ai.domain.errors import (
    IdempotencyKeyRequiredError,
    ValidationDomainError,
)
from legal_ai.schemas.validation import validate_idempotency_key


async def required_idempotency_key(
    idempotency_key: str | None = Header(default=None, alias="Idempotency-Key"),
) -> str:
    """Require and validate an Idempotency-Key without inferring an actor."""
    if idempotency_key is None:
        raise IdempotencyKeyRequiredError()
    try:
        return validate_idempotency_key(idempotency_key)
    except ValueError as exc:
        raise ValidationDomainError(
            "Idempotency-Key tiene un formato inválido",
            details={"field": "Idempotency-Key"},
        ) from exc


def request_id_from(request: Request) -> str:
    """Read the technical request ID generated by middleware."""
    return str(getattr(request.state, "request_id", ""))
